# Generated by Django 3.2 on 2021-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cruise_name', models.CharField(max_length=100)),
                ('Cabins', models.IntegerField()),
                ('Cabin_types', models.CharField(max_length=100)),
                ('Capacity', models.IntegerField()),
                ('Year_of_built', models.DateField()),
                ('Price_per_individuals', models.IntegerField()),
                ('Starts_from', models.CharField(max_length=200)),
                ('Destination', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=500)),
                ('Image', models.ImageField(upload_to='media/images')),
            ],
        ),
    ]
