# Generated by Django 3.2 on 2021-04-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='Year_of_built',
            field=models.IntegerField(),
        ),
    ]
