# Generated by Django 3.2 on 2021-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hall_name', models.CharField(max_length=100)),
                ('Hall_type', models.CharField(max_length=100)),
                ('Number_of_seats', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Hall_Description', models.TextField(max_length=300)),
                ('Hall_image', models.ImageField(upload_to='media/images')),
            ],
        ),
    ]
