# Generated by Django 3.1.7 on 2021-05-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='TPrice',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
