# Generated by Django 3.1.7 on 2021-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_hall_hprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='FPrice',
            field=models.IntegerField(default=100),
        ),
    ]
